# Generated by Django 6.0.2 on 2026-03-01 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker_app', '0002_transactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='usre',
            new_name='user',
        ),
    ]
