# Generated by Django 6.0.2 on 2026-03-02 14:13
from django.db import migrations, models

class Migration(migrations.Migration):
    
    
    dependencies = [
        ('expense_tracker_app', '0003_rename_usre_transactions_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.CharField(choices=[('Income', 'INCOME'), ('Expense', 'EXPENSE')]),
        ),
    ]
