# Generated by Django 6.0.2 on 2026-03-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker_app', '0004_alter_transactions_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.CharField(choices=[('Income', 'INCOME'), ('Expense', 'EXPENSE')], max_length=20),
        ),
    ]
